export interface TeamProps {
  id: number
  name: string
  logo?: string
}

const teams: TeamProps[] = [
  { id: 1, name: 'Abilene Christian', logo: 'abilene-christian.svg' },
  { id: 2, name: 'Alabama', logo: 'alabama.svg' },
  { id: 3, name: 'Arkansas', logo: 'arkansas.svg' },
  { id: 4, name: 'Baylor', logo: 'baylor.svg' },
  { id: 5, name: 'Belmont', logo: 'belmont.svg' },
  { id: 6, name: 'BYU', logo: 'byu.svg' },
  { id: 7, name: 'Clemson', logo: 'clemson.svg' },
  { id: 8, name: 'Cleveland State', logo: 'cleveland-st.svg' },
  { id: 9, name: 'Colorado', logo: 'colorado.svg' },
  { id: 10, name: 'Creighton', logo: 'creighton.svg' },
  { id: 11, name: 'Eastern Washington', logo: 'eastern-wash.svg' },
  { id: 12, name: 'Florida', logo: 'florida.svg' },
  { id: 13, name: 'FSU', logo: 'florida-st.svg' },
  { id: 14, name: 'GA Tech', logo: 'georgia-tech.svg' },
  { id: 15, name: 'Gonzaga', logo: 'gonzaga.svg' },
  { id: 16, name: 'Grand Canyon', logo: 'grand-canyon.svg' },
  { id: 17, name: 'Houston', logo: 'houston.svg' },
  { id: 18, name: 'Illinois', logo: 'illinois.svg' },
  { id: 19, name: 'Iowa', logo: 'iowa.svg' },
  { id: 20, name: 'JMU', logo: 'james-madison.svg' },
  { id: 21, name: 'Kansas', logo: 'kansas.svg' },
  { id: 22, name: 'Liberty', logo: 'liberty.svg' },
  { id: 23, name: 'Louisville', logo: 'louisville.svg' },
  { id: 24, name: 'Loyola Chicago', logo: 'loyola-chicago.svg' },
  { id: 25, name: 'LSU', logo: 'lsu.svg' },
  { id: 26, name: 'Maryland', logo: 'maryland.svg' },
  { id: 27, name: 'Michigan', logo: 'michigan.svg' },
  { id: 28, name: 'Michigan State / UCLA' },
  { id: 29, name: 'Missouri', logo: 'missouri.svg' },
  { id: 30, name: 'Navy', logo: 'navy.svg' },
  { id: 31, name: 'Oklahoma', logo: 'oklahoma.svg' },
  { id: 32, name: 'Oklahoma State', logo: 'oklahoma-st.svg' },
  { id: 33, name: 'Ohio State', logo: 'ohio-st.svg' },
  { id: 34, name: 'Oregon', logo: 'oregon.svg' },
  { id: 35, name: 'Prairie View A&M / NC A&T' },
  { id: 36, name: 'Purdue', logo: 'purdue.svg' },
  { id: 37, name: 'Rutgers', logo: 'rutgers.svg' },
  { id: 38, name: 'San Diego State', logo: 'san-diego-st.svg' },
  { id: 39, name: 'Seton Hall / Drake' },
  { id: 40, name: 'Siena', logo: 'siena.svg' },
  { id: 41, name: 'South Dakota State', logo: 'south-dakota-st.svg' },
  { id: 42, name: 'St. Bonaventure', logo: 'st-bonaventure.svg' },
  { id: 43, name: 'Tennessee', logo: 'tennessee.svg' },
  { id: 44, name: 'Texas', logo: 'texas.svg' },
  { id: 45, name: 'Texas State / Bryant' },
  { id: 46, name: 'Texas Tech', logo: 'texas-tech.svg' },
  { id: 47, name: 'Toledo', logo: 'toledo.svg' },
  { id: 48, name: 'UCLA', logo: 'ucla.svg' },
  { id: 49, name: 'UConn', logo: 'uconn.svg' },
  { id: 50, name: 'UCSB', logo: 'uc-santa-barbara.svg' },
  { id: 51, name: 'UMBC', logo: 'umbc.svg' },
  { id: 52, name: 'UNC', logo: 'north-carolina.svg' },
  { id: 53, name: 'UNCG', logo: 'unc-greensboro.svg' },
  { id: 54, name: 'USC', logo: 'southern-california.svg' },
  { id: 55, name: 'VA Tech', logo: 'virginia-tech.svg' },
  { id: 56, name: 'VCU', logo: 'vcu.svg' },
  { id: 57, name: 'Villanova', logo: 'villanova.svg' },
  { id: 58, name: 'Virginia', logo: 'virginia.svg' },
  { id: 59, name: 'West Virginia', logo: 'west-virginia.svg' },
  { id: 60, name: 'Western Kentucky', logo: 'western-ky.svg' },
  { id: 61, name: 'Wichita State / Drake' },
  { id: 62, name: 'Winthrop', logo: 'winthrop.svg' },
  { id: 63, name: 'Wisconsin', logo: 'wisconsin.svg' },
  { id: 64, name: 'Xavier', logo: 'xavier.svg' },
  { id: 65, name: 'Ohio', logo: 'ohio.svg' },
  { id: 66, name: 'Virginia Tech', logo: 'virginia-tech.svg' },
  { id: 67, name: 'Utah State', logo: 'utah-st.svg' },
  { id: 68, name: 'North Texas', logo: 'north-texas.svg' },
  { id: 69, name: 'Colgate', logo: 'colgate.svg' },
  { id: 70, name: 'Oral Roberts', logo: 'oral-roberts.svg' },
  { id: 71, name: 'Hartford', logo: 'hartford.svg' },
  { id: 72, name: 'Syracuse', logo: 'syracuse.svg' },
  { id: 73, name: 'Oregon State', logo: 'oregon-st.svg' },
  { id: 74, name: 'Morehead State', logo: 'morehead-st.svg' },
  { id: 75, name: 'Drexel', logo: 'drexel.svg' },
  { id: 76, name: 'Georgetown', logo: 'georgetown.svg' },
  { id: 77, name: 'Iona', logo: 'iona.svg' },
  { id: 78, name: `Mt St Mary's / Texas Southern` },
  { id: 79, name: 'Norfolk St / Appalachian St' }
]

export const getTeam = (id: number): TeamProps => {
  return teams.find((t) => t.id === id)
}
