// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:05c23a67-107c-4f2b-8547-5cbea61d7775",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FvehtbeeZ",
    "aws_user_pools_web_client_id": "6vrd0se3q0jekjpjd100klu8jk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://i2oiof76vjbobofxg5qp4nfrty.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
