// tslint:disable
// this is an auto generated file. This will be overwritten

export const onCreateResult = `subscription OnCreateResult {
  onCreateResult {
    id
    superBowl
    tieBreaker
    afcConference
    nfcConference
    afcDivisional1
    afcDivisional2
    nfcDivisional1
    nfcDivisional2
    afcWildCard1
    afcWildCard2
    afcWildCard3
    nfcWildCard1
    nfcWildCard2
    nfcWildCard3
    _version
    _deleted
    _lastChangedAt
    createdAt
    updatedAt
  }
}
`;
export const onUpdateResult = `subscription OnUpdateResult {
  onUpdateResult {
    id
    superBowl
    tieBreaker
    afcConference
    nfcConference
    afcDivisional1
    afcDivisional2
    nfcDivisional1
    nfcDivisional2
    afcWildCard1
    afcWildCard2
    afcWildCard3
    nfcWildCard1
    nfcWildCard2
    nfcWildCard3
    _version
    _deleted
    _lastChangedAt
    createdAt
    updatedAt
  }
}
`;
export const onDeleteResult = `subscription OnDeleteResult {
  onDeleteResult {
    id
    superBowl
    tieBreaker
    afcConference
    nfcConference
    afcDivisional1
    afcDivisional2
    nfcDivisional1
    nfcDivisional2
    afcWildCard1
    afcWildCard2
    afcWildCard3
    nfcWildCard1
    nfcWildCard2
    nfcWildCard3
    _version
    _deleted
    _lastChangedAt
    createdAt
    updatedAt
  }
}
`;
export const onCreateEntry = `subscription OnCreateEntry {
  onCreateEntry {
    id
    username
    superBowl
    tieBreaker
    afcConference
    nfcConference
    afcDivisional1
    afcDivisional2
    nfcDivisional1
    nfcDivisional2
    afcWildCard1
    afcWildCard2
    afcWildCard3
    nfcWildCard1
    nfcWildCard2
    nfcWildCard3
    owner
    _version
    _deleted
    _lastChangedAt
    createdAt
    updatedAt
  }
}
`;
export const onUpdateEntry = `subscription OnUpdateEntry {
  onUpdateEntry {
    id
    username
    superBowl
    tieBreaker
    afcConference
    nfcConference
    afcDivisional1
    afcDivisional2
    nfcDivisional1
    nfcDivisional2
    afcWildCard1
    afcWildCard2
    afcWildCard3
    nfcWildCard1
    nfcWildCard2
    nfcWildCard3
    owner
    _version
    _deleted
    _lastChangedAt
    createdAt
    updatedAt
  }
}
`;
export const onDeleteEntry = `subscription OnDeleteEntry {
  onDeleteEntry {
    id
    username
    superBowl
    tieBreaker
    afcConference
    nfcConference
    afcDivisional1
    afcDivisional2
    nfcDivisional1
    nfcDivisional2
    afcWildCard1
    afcWildCard2
    afcWildCard3
    nfcWildCard1
    nfcWildCard2
    nfcWildCard3
    owner
    _version
    _deleted
    _lastChangedAt
    createdAt
    updatedAt
  }
}
`;
